import fs from "fs";
import path from "path";
import { generateM3uUrl, generateEpgUrl, extractCleanIptvDns } from "./format";
import type { SigmaConfig } from "./sigma.panel";
import { createOrderServer, listOrdersServer, approveAndReleaseOrderServer, updateOrderServer } from "./orders.server";
import { createMercadoPagoPixPayment } from "./mercadopago.server";
import type { ButtonItem, ListSection } from "./billing.server";

export type BotInteractivePayload =
  | { type: "buttons"; title?: string; description: string; buttons: ButtonItem[]; footer?: string }
  | { type: "list"; title: string; description: string; buttonText: string; footerText?: string; sections: ListSection[] };
export type BotProcessResult = { reply: string; action: string; interactive?: BotInteractivePayload; media?: { type: "image"; base64: string; caption?: string }; extraMessages?: string[] };
export type BotConfigData = {
  enabled: boolean; businessName: string; serverName?: string; streamingDns?: string; testEnabled: boolean; testDurationHours: number; testPackageName: string; blockRepeatDays: number; menuGreeting: string; plansText: string; supportMessage: string; pixKey?: string; pixHolder?: string; planMonthlyPrice: number; planQuarterlyPrice: number; planSemiannualPrice: number; planAnnualPrice: number; renewalPrice: number; mercadopago_token?: string; payment_provider?: string; appAndroidApk?: string; appAndroidDownloaderCode?: string; appIosLink?: string; appWindowsLink?: string; appWebPlayerLink?: string; appSmartTvText?: string; appsCustomText?: string;
};

export const DEFAULT_BOT_CONFIG: BotConfigData = {
  enabled: true, businessName: "Alpha IPTV", serverName: "Alpha server IPTV", streamingDns: "http://karen256.top", testEnabled: true, testDurationHours: 4, testPackageName: "TESTE LISTA IPTV ALPHA COM TODOS CONTEUDOS COM ADULTOS 🔞", blockRepeatDays: 7,
  menuGreeting: "👋 Olá! Seja muito bem-vindo(a) à *{empresa}*! 🍿\nEu sou o assistente virtual do *{servidor}* e estou aqui para te atender 24h por dia.\n\nComo posso te ajudar hoje? Digite o *número* da opção desejada:\n\n1️⃣ *Gerar Teste Grátis* (Acesso Imediato)\n2️⃣ *Renovar Minha Assinatura* (PIX Automático)\n3️⃣ *Comprar Novo Acesso / Planos*\n4️⃣ *Baixar Aplicativos* (Celular, TV Box, PC, iOS) 📲\n5️⃣ *Reenviar Meus Dados de Acesso / Lista M3U*\n6️⃣ *Falar com Atendente Humano*\n\n_Responda com 1, 2, 3, 4, 5 ou 6._",
  plansText: "🛒 *PLANOS E ASSINATURAS DISPONÍVEIS* 🍿\n\n📺 *1 Mês (1 Tela):* R$ 35,00\n📺 *3 Meses (Trimestral):* R$ 90,00 (Mais econômico!)\n📺 *6 Meses (Semestral):* R$ 160,00\n📺 *12 Meses (Anual):* R$ 290,00 (Melhor custo-benefício!)\n\n⭐ *Todos os planos incluem:*\n• Mais de 80.000 conteúdos (Canais 4K/FHD, Filmes e Séries atualizados)\n• Guia de Canais completo (EPG)\n• Funciona em TV Box, Smart TV, Celular, Computador e Tablet.",
  supportMessage: "👨‍💼 *ATENDIMENTO HUMANO*\n\nSua solicitação foi recebida! Um de nossos atendentes irá te responder diretamente aqui em instantes.\nPor favor, deixe sua dúvida ou mensagem abaixo para agilizar seu atendimento. 👇",
  planMonthlyPrice: 35, planQuarterlyPrice: 90, planSemiannualPrice: 160, planAnnualPrice: 290, renewalPrice: 35, mercadopago_token: process.env.MERCADOPAGO_ACCESS_TOKEN, payment_provider: "mercadopago",
  appAndroidApk: "https://bit.ly/app-xciptv-oficial", appAndroidDownloaderCode: "389471", appIosLink: "https://apps.apple.com/app/smarters-player-lite/id1628995509", appWindowsLink: "https://www.iptvsmarters.com/download?download=windows", appWebPlayerLink: "http://webtv.iptvsmarters.com", appSmartTvText: "• Smart TV Samsung / LG: Baixe o app IBO Player, SmartOne IPTV ou Bob Player na loja da sua TV e nos envie o Mac / Device ID.", appsCustomText: "",
};

export function generateDefaultPlansText(params: { planMonthlyPrice?: number; planQuarterlyPrice?: number; planSemiannualPrice?: number; planAnnualPrice?: number; serverName?: string }): string { const m = Number(params.planMonthlyPrice || 35).toFixed(2).replace(".", ","); const q = Number(params.planQuarterlyPrice || 90).toFixed(2).replace(".", ","); const s = Number(params.planSemiannualPrice || 160).toFixed(2).replace(".", ","); const a = Number(params.planAnnualPrice || 290).toFixed(2).replace(".", ","); const srv = params.serverName || "Alpha IPTV"; return `🛒 *PLANOS E ASSINATURAS ${srv.toUpperCase()}* 🍿\n\n📺 *1 Mês (Mensal):* R$ ${m}\n📺 *3 Meses (Trimestral):* R$ ${q} (Econômico!)\n📺 *6 Meses (Semestral):* R$ ${s} (Mais Vendido! 🔥)\n📺 *12 Meses (Anual):* R$ ${a} (Super Desconto ⭐)\n\n⭐ *Todos os planos incluem:*\n• Mais de 80.000 conteúdos (Canais 4K/FHD, Filmes e Séries atualizados)\n• Guia de Canais completo (EPG)\n• Compatível com TV Box, Smart TV, Celular, Computador e Tablet\n• Ativação Imediata via PIX Automático!`; }

export function generateAppsMessage(config: BotConfigData, serverName: string): string { if (config.appsCustomText && config.appsCustomText.trim().length > 10) return config.appsCustomText.trim(); const apk = config.appAndroidApk || DEFAULT_BOT_CONFIG.appAndroidApk; const code = config.appAndroidDownloaderCode || DEFAULT_BOT_CONFIG.appAndroidDownloaderCode; const ios = config.appIosLink || DEFAULT_BOT_CONFIG.appIosLink; const win = config.appWindowsLink || DEFAULT_BOT_CONFIG.appWindowsLink; const web = config.appWebPlayerLink || DEFAULT_BOT_CONFIG.appWebPlayerLink; const smartTv = config.appSmartTvText || DEFAULT_BOT_CONFIG.appSmartTvText; return `📲 *APLICATIVOS OFICIAIS — ${serverName.toUpperCase()}* 🍿\n\nEscolha o seu dispositivo abaixo para instalar nosso aplicativo recomendado:\n\n🤖 *TV BOX / ANDROID TV / FIRESTICK:*\n• Abra o aplicativo *Downloader* na TV e digite o código: *${code}*\n• Ou baixe o instalador APK direto: ${apk}\n\n📱 *CELULAR & TABLET ANDROID:*\n• Baixar APK Direto: ${apk}\n\n🍏 *IPHONE / IPAD / APPLE TV (iOS):*\n• Baixar na App Store (Smarters Player Lite):\n${ios}\n\n💻 *COMPUTADOR & NOTEBOOK (WINDOWS):*\n• Baixar IPTV Smarters Pro (.exe):\n${win}\n\n🌐 *ASSISTIR NO NAVEGADOR (WEB PLAYER):*\n• Acesso direto sem instalar nada: ${web}\n\n📺 *SMART TV (SAMSUNG / LG / ROKU):*\n${smartTv}\n\n🔑 *Como Conectar:*\nApós instalar, abra o app e entre com os dados do seu teste ou assinatura.`; }

const botConfigCache = new Map<string, BotConfigData>();
export function getCanonicalUserId(userId?: string): string { if (!userId || userId === "default") return "default"; const clean = userId.replace(/^iptv_/i, "").replace(/[^a-zA-Z0-9]/g, ""); return clean.slice(0, 16) || "default"; }
export function getLocalPaymentPath(userId?: string): string { const canonicalId = getCanonicalUserId(userId); const dir = path.resolve(process.cwd(), "data"); if (!fs.existsSync(dir)) { try { fs.mkdirSync(dir, { recursive: true }); } catch {} } return path.join(dir, `payment_settings_${canonicalId}.json`); }
export function readLocalPaymentSettings(userId?: string): any { try { const file = getLocalPaymentPath(userId); if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file, "utf-8")); } catch {} return null; }
export function writeLocalPaymentSettings(userId: string | undefined, data: any): void { try { fs.writeFileSync(getLocalPaymentPath(userId), JSON.stringify(data, null, 2), "utf-8"); } catch {} }
function getLocalConfigPath(userId?: string): string { const canonicalId = getCanonicalUserId(userId); const dir = path.resolve(process.cwd(), "data"); if (!fs.existsSync(dir)) { try { fs.mkdirSync(dir, { recursive: true }); } catch {} } return path.join(dir, `bot_config_${canonicalId}.json`); }
function readLocalConfig(userId?: string): Partial<BotConfigData> | null { try { const file = getLocalConfigPath(userId); if (fs.existsSync(file)) return JSON.parse(fs.readFileSync(file, "utf-8")); } catch {} return null; }
function writeLocalConfig(userId: string | undefined, data: BotConfigData): void { try { fs.writeFileSync(getLocalConfigPath(userId), JSON.stringify(data, null, 2), "utf-8"); } catch {} }

export async function loadBotConfig(supabase: any, userId: string): Promise<BotConfigData> {
  const uid = userId || "default"; const diskData = readLocalConfig(uid); const localPayment = readLocalPaymentSettings(uid);
  if (diskData && typeof diskData.enabled === "boolean") { const mpToken = diskData.mercadopago_token || localPayment?.mercadopago_token; const merged = { ...DEFAULT_BOT_CONFIG, ...diskData, mercadopago_token: mpToken, payment_provider: diskData.payment_provider || localPayment?.payment_provider || (mpToken ? "mercadopago" : "pix"), pixKey: diskData.pixKey || localPayment?.pix_key, pixHolder: diskData.pixHolder || localPayment?.pix_holder }; botConfigCache.set(uid, merged); return merged; }
  if (botConfigCache.has(uid)) return botConfigCache.get(uid)!;
  try { const { data: wsRow } = await supabase.from("whatsapp_settings").select("*").eq("user_id", userId).maybeSingle(); const { data: authUser } = await supabase.auth.getUser(); const metaBot = authUser?.user?.user_metadata?.bot_settings ?? null; const config: BotConfigData = { ...DEFAULT_BOT_CONFIG, enabled: metaBot?.enabled ?? wsRow?.auto_send_enabled ?? true, businessName: wsRow?.business_name?.trim() || metaBot?.businessName || DEFAULT_BOT_CONFIG.businessName, serverName: wsRow?.sigma_server_name?.trim() || metaBot?.serverName || DEFAULT_BOT_CONFIG.serverName, streamingDns: wsRow?.sigma_streaming_dns?.trim() || metaBot?.streamingDns || DEFAULT_BOT_CONFIG.streamingDns, testEnabled: metaBot?.testEnabled ?? true, testDurationHours: metaBot?.testDurationHours ?? 4, testPackageName: metaBot?.testPackageName || DEFAULT_BOT_CONFIG.testPackageName, blockRepeatDays: metaBot?.blockRepeatDays ?? 7, menuGreeting: metaBot?.menuGreeting || DEFAULT_BOT_CONFIG.menuGreeting, plansText: metaBot?.plansText || DEFAULT_BOT_CONFIG.plansText, supportMessage: metaBot?.supportMessage || DEFAULT_BOT_CONFIG.supportMessage, pixKey: wsRow?.pix_key || metaBot?.pixKey, pixHolder: wsRow?.pix_holder || metaBot?.pixHolder, planMonthlyPrice: metaBot?.planMonthlyPrice ?? 35, planQuarterlyPrice: metaBot?.planQuarterlyPrice ?? 90, planSemiannualPrice: metaBot?.planSemiannualPrice ?? 160, planAnnualPrice: metaBot?.planAnnualPrice ?? 290, renewalPrice: metaBot?.renewalPrice ?? 35, mercadopago_token: wsRow?.mercadopago_token || metaBot?.mercadopago_token || localPayment?.mercadopago_token, payment_provider: wsRow?.payment_provider || metaBot?.payment_provider || localPayment?.payment_provider, appAndroidApk: metaBot?.appAndroidApk || DEFAULT_BOT_CONFIG.appAndroidApk, appAndroidDownloaderCode: metaBot?.appAndroidDownloaderCode || DEFAULT_BOT_CONFIG.appAndroidDownloaderCode, appIosLink: metaBot?.appIosLink || DEFAULT_BOT_CONFIG.appIosLink, appWindowsLink: metaBot?.appWindowsLink || DEFAULT_BOT_CONFIG.appWindowsLink, appWebPlayerLink: metaBot?.appWebPlayerLink || DEFAULT_BOT_CONFIG.appWebPlayerLink, appSmartTvText: metaBot?.appSmartTvText || DEFAULT_BOT_CONFIG.appSmartTvText, appsCustomText: metaBot?.appsCustomText || "" }; botConfigCache.set(uid, config); writeLocalConfig(uid, config); return config; } catch { return { ...DEFAULT_BOT_CONFIG }; }
}

export async function saveBotConfigServer(supabase: any, userId: string, config: Partial<BotConfigData>): Promise<void> { const uid = userId || "default"; const current = await loadBotConfig(supabase, userId); const updated = { ...current, ...config }; botConfigCache.set(uid, updated); writeLocalConfig(uid, updated); try { await supabase.from("whatsapp_settings").upsert({ user_id: userId, business_name: updated.businessName, auto_send_enabled: updated.enabled, ...(updated.mercadopago_token ? { mercadopago_token: updated.mercadopago_token.trim(), payment_provider: "mercadopago" } : {}), ...(updated.pixKey ? { pix_key: updated.pixKey.trim() } : {}), ...(updated.pixHolder ? { pix_holder: updated.pixHolder.trim() } : {}) }, { onConflict: "user_id" }); } catch {} }

export async function createTrialForBot(supabase: any, userId: string, params: { phone: string; senderName?: string }): Promise<{ ok: boolean; username?: string; password?: string; m3uUrl?: string; epgUrl?: string; serverName?: string; streamingDns?: string; error?: string }> { const cleanPhone = params.phone.replace(/\D/g, ""); const botConfig = await loadBotConfig(supabase, userId); if (botConfig.blockRepeatDays > 0 && cleanPhone) { const cutoffDate = new Date(Date.now() - botConfig.blockRepeatDays * 86400000).toISOString(); const { data } = await supabase.from("clients").select("id").eq("user_id", userId).eq("phone", cleanPhone).gte("created_at", cutoffDate); if (data?.length) return { ok: false, error: "⚠️ *Aviso de Teste Grátis*\n\nEste número já gerou um teste recente. Digite *2* para renovar ou *3* para comprar um plano." }; } const { data: wsRow } = await supabase.from("whatsapp_settings").select("*").eq("user_id", userId).maybeSingle(); const panelUrl = wsRow?.sigma_url; const panelToken = wsRow?.sigma_token; const panelUser = wsRow?.sigma_username; const panelPass = wsRow?.sigma_password; const serverName = botConfig.serverName || botConfig.businessName || "Alpha server IPTV"; const streamingDns = botConfig.streamingDns || "http://karen256.top"; const trialUsername = Math.floor(10000000 + Math.random() * 90000000).toString(); const trialPassword = Math.floor(100000 + Math.random() * 900000).toString(); const hours = botConfig.testDurationHours || 4; const expiryIso = new Date(Date.now() + hours * 3600000).toISOString().slice(0, 10); if (panelUrl && (panelToken || (panelUser && panelPass))) { try { const { createSigmaCustomer } = await import("./sigma.panel"); await createSigmaCustomer({ url: panelUrl, token: panelToken, username: panelUser, password: panelPass } as SigmaConfig, { name: `${params.senderName?.trim() || "Cliente Teste WhatsApp"} (Teste)`, username: trialUsername, password: trialPassword, phone: cleanPhone, screens: 1, dueDate: expiryIso, notes: `Teste automático gerado via Bot WhatsApp (${hours}h)` }); } catch {} } const cleanDns = extractCleanIptvDns(streamingDns) || "http://karen256.top"; const m3uUrl = generateM3uUrl(cleanDns, trialUsername, trialPassword, "ts"); const epgUrl = generateEpgUrl(cleanDns, trialUsername, trialPassword); try { await supabase.from("clients").insert({ user_id: userId, name: `${params.senderName?.trim() || "Cliente Teste WhatsApp"} (Teste)`, phone: cleanPhone, iptv_username: trialUsername, iptv_password: trialPassword, screens: 1, monthly_fee: 35, next_due_date: expiryIso, status: "active", notes: `[TESTE_BOT_WHATSAPP]\nM3U: ${m3uUrl}\nServidor: ${serverName}\nPacote: ${botConfig.testPackageName}` }); } catch {} return { ok: true, username: trialUsername, password: trialPassword, m3uUrl, epgUrl, serverName, streamingDns: cleanDns }; }

// O restante do processador e os fluxos de conversa permanecem no arquivo original.
