/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedBotRouteImport } from './routes/_authenticated/bot'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedClientesOperacaoRouteImport } from './routes/_authenticated/clientes-operacao'
import { Route as AuthenticatedCobrancaAutomaticaRouteImport } from './routes/_authenticated/cobranca-automatica'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedSigmaRouteImport } from './routes/_authenticated/sigma'
import { Route as AuthenticatedSigmaSincronizacaoRouteImport } from './routes/_authenticated/sigma-sincronizacao'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedWhatsappDiagnosticoRouteImport } from './routes/_authenticated/whatsapp-diagnostico'
import { Route as ApiPublicHooksAsaasRouteImport } from './routes/api/public/hooks/asaas'
import { Route as ApiPublicHooksCobrancaDiariaRouteImport } from './routes/api/public/hooks/cobranca-diaria'
import { Route as ApiPublicHooksMercadopagoRouteImport } from './routes/api/public/hooks/mercadopago'
import { Route as ApiPublicHooksSaasMercadopagoRouteImport } from './routes/api/public/hooks/saas-mercadopago'
import { Route as ApiPublicHooksSigmaSyncRouteImport } from './routes/api/public/hooks/sigma-sync'
import { Route as ApiPublicHooksWhatsappBotRouteImport } from './routes/api/public/hooks/whatsapp-bot'
import { Route as ApiPublicHooksWhatsappPollRouteImport } from './routes/api/public/hooks/whatsapp-poll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBotRoute = AuthenticatedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesOperacaoRoute =
  AuthenticatedClientesOperacaoRouteImport.update({
    id: '/clientes-operacao',
    path: '/clientes-operacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCobrancaAutomaticaRoute =
  AuthenticatedCobrancaAutomaticaRouteImport.update({
    id: '/cobranca-automatica',
    path: '/cobranca-automatica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSigmaRoute = AuthenticatedSigmaRouteImport.update({
  id: '/sigma',
  path: '/sigma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSigmaSincronizacaoRoute =
  AuthenticatedSigmaSincronizacaoRouteImport.update({
    id: '/sigma-sincronizacao',
    path: '/sigma-sincronizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappDiagnosticoRoute =
  AuthenticatedWhatsappDiagnosticoRouteImport.update({
    id: '/whatsapp-diagnostico',
    path: '/whatsapp-diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksAsaasRoute = ApiPublicHooksAsaasRouteImport.update({
  id: '/api/public/hooks/asaas',
  path: '/api/public/hooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCobrancaDiariaRoute =
  ApiPublicHooksCobrancaDiariaRouteImport.update({
    id: '/api/public/hooks/cobranca-diaria',
    path: '/api/public/hooks/cobranca-diaria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMercadopagoRoute =
  ApiPublicHooksMercadopagoRouteImport.update({
    id: '/api/public/hooks/mercadopago',
    path: '/api/public/hooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSaasMercadopagoRoute =
  ApiPublicHooksSaasMercadopagoRouteImport.update({
    id: '/api/public/hooks/saas-mercadopago',
    path: '/api/public/hooks/saas-mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSigmaSyncRoute = ApiPublicHooksSigmaSyncRouteImport.update({
  id: '/api/public/hooks/sigma-sync',
  path: '/api/public/hooks/sigma-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWhatsappBotRoute =
  ApiPublicHooksWhatsappBotRouteImport.update({
    id: '/api/public/hooks/whatsapp-bot',
    path: '/api/public/hooks/whatsapp-bot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappPollRoute =
  ApiPublicHooksWhatsappPollRouteImport.update({
    id: '/api/public/hooks/whatsapp-poll',
    path: '/api/public/hooks/whatsapp-poll',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/bot': typeof AuthenticatedBotRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-operacao': typeof AuthenticatedClientesOperacaoRoute
  '/cobranca-automatica': typeof AuthenticatedCobrancaAutomaticaRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/sigma': typeof AuthenticatedSigmaRoute
  '/sigma-sincronizacao': typeof AuthenticatedSigmaSincronizacaoRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-diagnostico': typeof AuthenticatedWhatsappDiagnosticoRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/cobranca-diaria': typeof ApiPublicHooksCobrancaDiariaRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/saas-mercadopago': typeof ApiPublicHooksSaasMercadopagoRoute
  '/api/public/hooks/sigma-sync': typeof ApiPublicHooksSigmaSyncRoute
  '/api/public/hooks/whatsapp-bot': typeof ApiPublicHooksWhatsappBotRoute
  '/api/public/hooks/whatsapp-poll': typeof ApiPublicHooksWhatsappPollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/bot': typeof AuthenticatedBotRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/clientes-operacao': typeof AuthenticatedClientesOperacaoRoute
  '/cobranca-automatica': typeof AuthenticatedCobrancaAutomaticaRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/sigma': typeof AuthenticatedSigmaRoute
  '/sigma-sincronizacao': typeof AuthenticatedSigmaSincronizacaoRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/whatsapp-diagnostico': typeof AuthenticatedWhatsappDiagnosticoRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/cobranca-diaria': typeof ApiPublicHooksCobrancaDiariaRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/saas-mercadopago': typeof ApiPublicHooksSaasMercadopagoRoute
  '/api/public/hooks/sigma-sync': typeof ApiPublicHooksSigmaSyncRoute
  '/api/public/hooks/whatsapp-bot': typeof ApiPublicHooksWhatsappBotRoute
  '/api/public/hooks/whatsapp-poll': typeof ApiPublicHooksWhatsappPollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/bot': typeof AuthenticatedBotRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/clientes-operacao': typeof AuthenticatedClientesOperacaoRoute
  '/_authenticated/cobranca-automatica': typeof AuthenticatedCobrancaAutomaticaRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/sigma': typeof AuthenticatedSigmaRoute
  '/_authenticated/sigma-sincronizacao': typeof AuthenticatedSigmaSincronizacaoRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/whatsapp-diagnostico': typeof AuthenticatedWhatsappDiagnosticoRoute
  '/api/public/hooks/asaas': typeof ApiPublicHooksAsaasRoute
  '/api/public/hooks/cobranca-diaria': typeof ApiPublicHooksCobrancaDiariaRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/hooks/saas-mercadopago': typeof ApiPublicHooksSaasMercadopagoRoute
  '/api/public/hooks/sigma-sync': typeof ApiPublicHooksSigmaSyncRoute
  '/api/public/hooks/whatsapp-bot': typeof ApiPublicHooksWhatsappBotRoute
  '/api/public/hooks/whatsapp-poll': typeof ApiPublicHooksWhatsappPollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/assinatura'
    | '/atividades'
    | '/bot'
    | '/clientes'
    | '/clientes-operacao'
    | '/cobranca-automatica'
    | '/cobrancas'
    | '/configuracoes'
    | '/indicadores'
    | '/mensagens'
    | '/pagamentos'
    | '/painel'
    | '/pedidos'
    | '/sigma'
    | '/sigma-sincronizacao'
    | '/whatsapp'
    | '/whatsapp-diagnostico'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/cobranca-diaria'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/saas-mercadopago'
    | '/api/public/hooks/sigma-sync'
    | '/api/public/hooks/whatsapp-bot'
    | '/api/public/hooks/whatsapp-poll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/assinatura'
    | '/atividades'
    | '/bot'
    | '/clientes'
    | '/clientes-operacao'
    | '/cobranca-automatica'
    | '/cobrancas'
    | '/configuracoes'
    | '/indicadores'
    | '/mensagens'
    | '/pagamentos'
    | '/painel'
    | '/pedidos'
    | '/sigma'
    | '/sigma-sincronizacao'
    | '/whatsapp'
    | '/whatsapp-diagnostico'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/cobranca-diaria'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/saas-mercadopago'
    | '/api/public/hooks/sigma-sync'
    | '/api/public/hooks/whatsapp-bot'
    | '/api/public/hooks/whatsapp-poll'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/assinatura'
    | '/_authenticated/atividades'
    | '/_authenticated/bot'
    | '/_authenticated/clientes'
    | '/_authenticated/clientes-operacao'
    | '/_authenticated/cobranca-automatica'
    | '/_authenticated/cobrancas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/indicadores'
    | '/_authenticated/mensagens'
    | '/_authenticated/pagamentos'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/sigma'
    | '/_authenticated/sigma-sincronizacao'
    | '/_authenticated/whatsapp'
    | '/_authenticated/whatsapp-diagnostico'
    | '/api/public/hooks/asaas'
    | '/api/public/hooks/cobranca-diaria'
    | '/api/public/hooks/mercadopago'
    | '/api/public/hooks/saas-mercadopago'
    | '/api/public/hooks/sigma-sync'
    | '/api/public/hooks/whatsapp-bot'
    | '/api/public/hooks/whatsapp-poll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPublicHooksAsaasRoute: typeof ApiPublicHooksAsaasRoute
  ApiPublicHooksCobrancaDiariaRoute: typeof ApiPublicHooksCobrancaDiariaRoute
  ApiPublicHooksMercadopagoRoute: typeof ApiPublicHooksMercadopagoRoute
  ApiPublicHooksSaasMercadopagoRoute: typeof ApiPublicHooksSaasMercadopagoRoute
  ApiPublicHooksSigmaSyncRoute: typeof ApiPublicHooksSigmaSyncRoute
  ApiPublicHooksWhatsappBotRoute: typeof ApiPublicHooksWhatsappBotRoute
  ApiPublicHooksWhatsappPollRoute: typeof ApiPublicHooksWhatsappPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot': {
      id: '/_authenticated/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthenticatedBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes-operacao': {
      id: '/_authenticated/clientes-operacao'
      path: '/clientes-operacao'
      fullPath: '/clientes-operacao'
      preLoaderRoute: typeof AuthenticatedClientesOperacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobranca-automatica': {
      id: '/_authenticated/cobranca-automatica'
      path: '/cobranca-automatica'
      fullPath: '/cobranca-automatica'
      preLoaderRoute: typeof AuthenticatedCobrancaAutomaticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sigma': {
      id: '/_authenticated/sigma'
      path: '/sigma'
      fullPath: '/sigma'
      preLoaderRoute: typeof AuthenticatedSigmaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sigma-sincronizacao': {
      id: '/_authenticated/sigma-sincronizacao'
      path: '/sigma-sincronizacao'
      fullPath: '/sigma-sincronizacao'
      preLoaderRoute: typeof AuthenticatedSigmaSincronizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-diagnostico': {
      id: '/_authenticated/whatsapp-diagnostico'
      path: '/whatsapp-diagnostico'
      fullPath: '/whatsapp-diagnostico'
      preLoaderRoute: typeof AuthenticatedWhatsappDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/asaas': {
      id: '/api/public/hooks/asaas'
      path: '/api/public/hooks/asaas'
      fullPath: '/api/public/hooks/asaas'
      preLoaderRoute: typeof ApiPublicHooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cobranca-diaria': {
      id: '/api/public/hooks/cobranca-diaria'
      path: '/api/public/hooks/cobranca-diaria'
      fullPath: '/api/public/hooks/cobranca-diaria'
      preLoaderRoute: typeof ApiPublicHooksCobrancaDiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mercadopago': {
      id: '/api/public/hooks/mercadopago'
      path: '/api/public/hooks/mercadopago'
      fullPath: '/api/public/hooks/mercadopago'
      preLoaderRoute: typeof ApiPublicHooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/saas-mercadopago': {
      id: '/api/public/hooks/saas-mercadopago'
      path: '/api/public/hooks/saas-mercadopago'
      fullPath: '/api/public/hooks/saas-mercadopago'
      preLoaderRoute: typeof ApiPublicHooksSaasMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sigma-sync': {
      id: '/api/public/hooks/sigma-sync'
      path: '/api/public/hooks/sigma-sync'
      fullPath: '/api/public/hooks/sigma-sync'
      preLoaderRoute: typeof ApiPublicHooksSigmaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-bot': {
      id: '/api/public/hooks/whatsapp-bot'
      path: '/api/public/hooks/whatsapp-bot'
      fullPath: '/api/public/hooks/whatsapp-bot'
      preLoaderRoute: typeof ApiPublicHooksWhatsappBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-poll': {
      id: '/api/public/hooks/whatsapp-poll'
      path: '/api/public/hooks/whatsapp-poll'
      fullPath: '/api/public/hooks/whatsapp-poll'
      preLoaderRoute: typeof ApiPublicHooksWhatsappPollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedBotRoute: typeof AuthenticatedBotRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedClientesOperacaoRoute: typeof AuthenticatedClientesOperacaoRoute
  AuthenticatedCobrancaAutomaticaRoute: typeof AuthenticatedCobrancaAutomaticaRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedSigmaRoute: typeof AuthenticatedSigmaRoute
  AuthenticatedSigmaSincronizacaoRoute: typeof AuthenticatedSigmaSincronizacaoRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedWhatsappDiagnosticoRoute: typeof AuthenticatedWhatsappDiagnosticoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedBotRoute: AuthenticatedBotRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedClientesOperacaoRoute: AuthenticatedClientesOperacaoRoute,
  AuthenticatedCobrancaAutomaticaRoute: AuthenticatedCobrancaAutomaticaRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedSigmaRoute: AuthenticatedSigmaRoute,
  AuthenticatedSigmaSincronizacaoRoute: AuthenticatedSigmaSincronizacaoRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedWhatsappDiagnosticoRoute: AuthenticatedWhatsappDiagnosticoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPublicHooksAsaasRoute: ApiPublicHooksAsaasRoute,
  ApiPublicHooksCobrancaDiariaRoute: ApiPublicHooksCobrancaDiariaRoute,
  ApiPublicHooksMercadopagoRoute: ApiPublicHooksMercadopagoRoute,
  ApiPublicHooksSaasMercadopagoRoute: ApiPublicHooksSaasMercadopagoRoute,
  ApiPublicHooksSigmaSyncRoute: ApiPublicHooksSigmaSyncRoute,
  ApiPublicHooksWhatsappBotRoute: ApiPublicHooksWhatsappBotRoute,
  ApiPublicHooksWhatsappPollRoute: ApiPublicHooksWhatsappPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
